In [ ]:
#Task-1
import numpy as np
def playRight(sequence,beats):
  for b in range(len(beats)):
    if beats[b]==1:
      temp=sequence[len(sequence)-1]
      for s in range(len(sequence)-1,0,-1):
        sequence[s]=sequence[s-1]
      sequence[0]=temp
  return sequence
sequence=np.array([10,20,30,40,50,60])
beats = np.array([1,0,0,1,0,1])
print(playRight(sequence,beats))

[40 50 60 10 20 30]


In [ ]:
#Task-2
import numpy as np
def discardCards(cards,number):
  for i in range(len(cards)):
    while cards[i]==number:
      for k in range(i,len(cards)-1):
        cards[k]=cards[k+1]
      cards[len(cards)-1]=0
  return cards
cards = np.array([1,2,3,2,8,2,2,5,7])
print(discardCards(cards,2))

[1 3 8 5 7 0 0 0 0]


In [ ]:
#Task-3
import numpy as np
def mergeLineup(pokemon_1, pokemon_2):
  output=np.zeros((len(pokemon_1)),dtype="int64")
  for i in range(len(pokemon_1)):
    if pokemon_1[i]==None:
      pokemon_1[i]=0
    if pokemon_2[i]==None:
      pokemon_2[i]=0
  k=0
  l=len(pokemon_2)-1
  while k<l:
    temp=pokemon_2[k]
    pokemon_2[k]=pokemon_2[l]
    pokemon_2[l]=temp
    k+=1
    l-=1
  for j in range(len(output)):
    output[j]=pokemon_1[j]+pokemon_2[j]
  return output
pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None])
print(mergeLineup(pokemon_1, pokemon_2))

[12  3 28 -8  5]


In [ ]:
#Task-4
import numpy as np
def balanceSalami(salami):
  sum=0
  check=0
  result=False
  for i in salami:
    sum+=i
  if sum%2==0:
    for j in salami:
      check+=j
      if check==sum//2:
        result=True
        break
  return result
salami = np.array([1, 1, 1, 2, 1])
print(balanceSalami(salami))

True


In [8]:
import numpy as np
def balanceSalami(salami):
  sum=0
  check1=check2=0
  result=False
  for i in salami:
    sum+=i
  if sum%2==0:
    for j in range(len(salami)):
      check1+=salami[j]
      if check1==sum//2:
        for k in range(j+1,len(salami)):
          check2+=salami[k]
        if check2==sum//2:
          return True
          break
  return result
salami = np.array([10, 3, 1, 2, 10])
print(balanceSalami(salami))

True


In [ ]:
#Task-5
import numpy as np
def protectSalami(salami):
  note_count=np.zeros(len(salami),dtype="int64")
  note=np.zeros(len(salami),dtype="int64")
  count=0
  result=False
  for i in range(len(salami)):
    temp=salami[i]
    if temp not in note:
     for j in range(i,len(salami)):
      if temp==salami[j]:
        count+=1
     note[i]=temp
    if count>=2:
     note_count[i]=count
    count=0
  i=0
  k=len(note_count)-1
  for i in range(len(note_count)):
    while i<k:
      if note_count[i]!=0:
        if note_count[i]==note_count[k]:
          result=True
          break
      k-=1
    if result==True:
        break
    k=len(note_count)-1
  return result
salami = np.array([4,5,6,6,4,3,6,4])
print(protectSalami(salami))

True


In [ ]:
#Task-5 Alternative
import numpy as np
def protectSalami(salami):
  max=0
  for i in salami:
    if i>max:
      max=i
  aux_array=[0]*(max+1)
  for i in salami:
    aux_array[i]+=1
  repeat= False
  for i in range(max+1):
    k=i+1
    for j in range(k,max+1):
      if aux_array[i]==aux_array[j] and aux_array[i]>1:
        repeat=True
        break
  return repeat
salami = np.array([3,4,6,3,4,7,4,6,8,6,6])
print(protectSalami(salami))

False


In [ ]:
#Task-6
import numpy as np
def waveYourFlag(arr):
  new_arr=np.zeros(len(arr),dtype="int64")
  odd_count=even_count=0
  odd=arr[arr%2!=0]
  even=arr[arr%2==0]
  for i in arr:
    if i%2==0:
      even_count+=1
    else:
      odd_count+=1
  if even_count>=odd_count:
    new_arr[::2]=even
    new_arr[1::2]=odd
  elif odd_count>even_count:
     new_arr[::2]=odd
     new_arr[1::2]=even
  return new_arr
arr = np.array([45,23,78,84,41])
print(waveYourFlag(arr))

[45 78 23 84 41]


In [ ]:
#Task-6 Alternative
import numpy as np
def waveYourFlag(arr):
  new_arr=np.zeros(len(arr),dtype="int64")
  odd=arr[arr%2!=0]
  even=arr[arr%2==0]
  even_index=odd_index=0
  if len(even)>=len(odd):
   for i in range(len(arr)):
    if i%2==0:
      new_arr[i]=even[even_index]
      even_index+=1
    else:
      new_arr[i]=odd[odd_index]
      odd_index+=1
  elif len(odd)>len(even):
    for j in range(len(arr)):
      if j%2==0:
        new_arr[j]=odd[odd_index]
        odd_index+=1
      else:
        new_arr[j]=even[even_index]
        even_index+=1
  return new_arr
arr = np.array([2,12,3,7,1])
print(waveYourFlag(arr))

[ 3  2  7 12  1]


In [ ]:
#Task-7(Part-2)
import numpy as np
def mean(arr):
  sum=0
  for i in arr:
    sum+=i
  m=round(sum/len(arr),12)
  return m
def sd(arr):
  m=mean(arr)
  sum1=0
  for i in arr:
    sum1+=(i-m)**2
  s=round((sum1/(len(arr)-1))**(0.5),2)
  return s
def away_from_the_mean(arr):
  m=mean(arr)
  s=sd(arr)
  new_arr=np.zeros(len(arr),dtype="int64")
  a=m-(1.5*s)
  b=m+(1.5*s)
  j=0
  for i in arr:
    if i<=a or i>=b:
      new_arr[j]=i
      j+=1
  final_arr=np.zeros(j,dtype="int64")
  for i in range(len(new_arr)):
    if new_arr[i]!=0:
      final_arr[i]=new_arr[i]
  return final_arr
arr=np.array([10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4])
print(mean(arr))
print(sd(arr))
print(away_from_the_mean(arr))

10.181818181818
7.96
[25 -5]
